-- Demonology.lua — GENERATED from specs/demonology/catalog.json. Do not edit this file.
--   uv run python -m wowkb.capart export catalog demonology
-- Data only: the validator is Catalog.lua and the reasoning is catalog.md.
-- Soul Shards are one of the seven NEVER-SECRET power types, so the largest decision in the
-- spec — do I have five shards for Tyrant — is an exact Lua comparison rather than a curve.
-- Base spell ids only: Bind unions base/override/tooltip/live into the row, so neither
-- transform needs a hardcoded override id.
local ADDON, ns = ...

ns.Catalog.Register{
  spec = 266,
  hero = 59,
  name = "Demonology / Diabolist",
  power = "SoulShards",
  break_before = "implosion",

  abilities = {
    { id = "power_siphon", spell = 264130 },
    { id = "grimoire", spell = 1276452, alt = { 1276467 } },
    { id = "summon_doomguard", spell = 1276672 },
    { id = "call_dreadstalkers", spell = 104316 },
    { id = "summon_demonic_tyrant", spell = 265187 },
    { id = "implosion", spell = 196277 },
    { id = "hand_of_guldan", spell = 105174 },
    { id = "demonbolt", spell = 264178 },
    { id = "shadow_bolt", spell = 686 },
    -- Aura dependencies only: these are not enhanced CDM entries and never enter Signal. They
    -- exist so a sealed display can name a subject — the count or the clock the CLIENT reads.
    -- cap never learns any of their values.
    { id = "demonic_core", spell = 264173, family = "auras" },
    { id = "wild_imp", spell = 296553, family = "auras" },
    -- Doom is a DEBUFF cap puts on the target, which is why it carries a unit. Its refresh
    -- window is the client's own arithmetic, per spell (V19).
    { id = "doom", spell = 460553, family = "auras", unit = "target" },
    -- The armed Art that transforms row 9 into Infernal Bolt. The id is TIER-3-SOURCED and a
    -- wrong aura id dies SILENT — the slot matches nothing forever, indistinguishable from a
    -- refusal (the cast-id/aura-id trap, KB 3.5.2). Flight question; @verify-ingame on the id.
    { id = "art_mother_of_chaos", spell = 432794, family = "auras" },
  },

  -- Node + entry from knowledge/classes/warlock/demonology/talents.json @ 12.1. This is what
  -- talent.to_hell_and_back and talent.doom in the APL mean, read as themselves rather than
  -- through a proxy (Talents.lua explains why IsSpellKnown and charge counts are both refused).
  -- `spell` is documentation only — nothing resolves through it.
  talents = {
    { id = "to_hell_and_back", node = 110199, entry = 136728, spell = 1281511 },
    { id = "doom", node = 110200, entry = 136729, spell = 460551 },
    { id = "reign_of_tyranny", node = 110201, entry = 136730, spell = 1276748 },
  },

  -- Entry order IS the authored priority, and it is the flattened actions.diabolist with one
  -- swap. Catalog.OrderCheck compares it against Blizzard's layoutIndex, which stopped being
  -- the drawn order when Anchor shipped — so read its verdict as `the saved layout disagrees`,
  -- never as `the row on screen disagrees`.
  entries = {
    -- 1 · power_siphon. Its rung gate is buff.demonic_core.stack<=1, which is a SEALED count —
    -- so the row carries no readable cue at all and the display does the whole of the work.
    -- Below two Cores the band draws nothing and the row is an ordinary candidate; at two it
    -- hatches and marks itself, which is the row RULED OUT by a fact cap never read.
    { id = "power_siphon", ability = "power_siphon",
      markers = {
        { id = "ps_cores_banked",
          display = {
            ability = "demonic_core",
            bands = {
              {
                draw = "none",
                threshold = 0,
              },
              {
                draw = "mark",
                hatch = true,
                polarity = "negative",
                threshold = 2,
              },
            },
            kind = "sealed-count-bands",
          },
        },
      },
    },
    -- 2 · grimoire. A CHOICE NODE **and** the base of a transform — two independent facts, both
    -- true. The choice: both ids have their own Essential row and exactly one exists on a
    -- build, so the second goes in `alt` rather than through R7. The transform: whichever one
    -- exists becomes a dispel while its OWN cooldown runs — Imp Lord `1276452` → Singe Magic
    -- `132411` via override row `1276623`, Fel Ravager `1276467` → Devour Magic `388215` via
    -- `1276610`, both `EffectAura` 333, misc-form. So this row is never swiped by the
    -- Grimoire's 120 s: any swipe on it is the dispel's own 15 s. Cue K is what rules the row
    -- out instead.
    { id = "grimoire", ability = "grimoire",
      markers = {
        { id = "grimoire_awaits_shards",
          cue = "building",
          when = { { "ready", "summon_demonic_tyrant" }, { "resource", "<=", 4 } },
        },
        -- Cue K, and it reads this row's OWN identity — `ha_banks_bulwark` and `star_counter`
        -- are the shape, not cue D, which reads another row's. `overrideSpellID ~= spellID`
        -- here means the Grimoire's cooldown is running and the button on the icon is the
        -- dispel it becomes. cap's overlay reads the ROTATION; while the row is the dispel it
        -- is not the rotation entry the reader is looking for, so `blocked` says *this is not
        -- your Grimoire* — a statement about identity, never advice to avoid a castable button.
        { id = "grimoire_shows_dispel",
          cue = "blocked",
          when = { { "identity", "grimoire", "transformed" } },
        },
        -- V21, and it is the fact cue K leaves out — so it says it in cue K's own badge rather
        -- than beside it. Cue K rules this row out on identity; it says nothing about WHEN the
        -- row stops being the dispel, which is what a ramp is waiting for. Since 2026-08-28 the
        -- two are one statement: this marker declares `blocked`, and a `blocked` badge whose
        -- block is a cooldown draws that cooldown live — a red radial on the real remaining
        -- with a white countdown in it — instead of `timer_CW_50`, a picture of a clock face
        -- frozen at 50 % on a row where the real remaining exists and is reachable. `baseoncd`
        -- is the readable half — `C_Spell.GetSpellCooldown(baseID).isActive`, NeverSecret and
        -- plain in restricted combat — and it gates a badge whose arc and numeral the CLIENT
        -- draws off the base spell's own duration object, which cap hands over and never reads.
        -- ⚠ The dial reads the BOUND ROW's base id, not this declaration's `spell`: the entry
        -- covers both halves of a choice node through `alt`, so on a Fel Ravager build the
        -- declared id is the wrong half. The `ability` here names the subject, not the spell
        -- that is read.
        { id = "grimoire_base_cooldown",
          cue = "blocked",
          when = { { "baseoncd", "grimoire" } },
          display = {
            ability = "grimoire",
            kind = "sealed-base-cooldown",
          },
        },
        -- The band that makes the Grimoire's own hold legible, and the second display on this
        -- row to draw as a live dial. While the Grimoire is READY and Tyrant's cooldown is
        -- inside (3, 10), the client paints `blocked` and the badge is Tyrant's remaining — the
        -- thing the reader is actually waiting on. ⚠ The `!baseoncd` term is load-bearing and
        -- not decoration: this row is never swiped (the button on it is the dispel, with its
        -- own 15 s), so without it the band would arm while the Grimoire itself is on cooldown
        -- and two dials would claim the same badge. `baseoncd` is the one readable term that
        -- says which of the two is the live question.
        { id = "grimoire_awaits_tyrant",
          cue = "blocked",
          when = { { "talent", "reign_of_tyranny" }, { "baseoncd", "grimoire", negate = true } },
          display = {
            ability = "summon_demonic_tyrant",
            beyond = 3,
            kind = "sealed-cooldown-range",
            within = 10,
          },
        },
      },
    },
    -- 3 · summon_doomguard. Midnight-new. Cue I here is uniformity with the block, not played
    -- experience — the least-tested marker in this catalog.
    { id = "summon_doomguard", ability = "summon_doomguard",
      markers = {
        { id = "doomguard_awaits_shards",
          cue = "building",
          when = { { "ready", "summon_demonic_tyrant" }, { "resource", "<=", 4 } },
        },
      },
    },
    -- 4 · call_dreadstalkers. Cue I is the block's shared readable hold; cue J is the TWO-SIDED
    -- sealed band — hold while Tyrant's remaining is inside (10.5, 21.5), rung 6's own dead
    -- zone at S4's unhasted 1.5 s floor, Reign-gated.
    { id = "call_dreadstalkers", ability = "call_dreadstalkers",
      markers = {
        { id = "dreadstalkers_awaits_shards",
          cue = "building",
          when = { { "ready", "summon_demonic_tyrant" }, { "resource", "<=", 4 } },
        },
        { id = "dreadstalkers_awaits_tyrant",
          cue = "blocked",
          when = { { "talent", "reign_of_tyranny" } },
          display = {
            ability = "summon_demonic_tyrant",
            beyond = 10.5,
            kind = "sealed-cooldown-range",
            within = 21.5,
          },
        },
      },
    },
    -- 5 · summon_demonic_tyrant. The single biggest decision in the spec, and it is READABLE:
    -- rung 8 is soul_shard=5, read as a hold. Gated on readiness because a hold badge on a
    -- greyed icon says nothing.
    { id = "summon_demonic_tyrant", ability = "summon_demonic_tyrant",
      markers = {
        { id = "tyrant_awaits_shards",
          cue = "building",
          when = { { "ready", "summon_demonic_tyrant" }, { "resource", "<=", 4 } },
        },
      },
    },
    -- 6 · implosion. Two halves of one rung, split exactly on the readable/sealed line:
    -- active_enemies>2|talent.to_hell_and_back is readable and is the cue; wild_imps.stack>=6
    -- is sealed and is the display. The display is V17's COMPLEMENT — it draws BELOW the
    -- threshold and clears at it — and it is the first time a sealed fact enters elimination
    -- rather than merely being displayed.
    { id = "implosion", ability = "implosion",
      markers = {
        { id = "implosion_st_only",
          cue = "aoe_only",
          when = { { "aoe", negate = true }, { "talent", "to_hell_and_back", negate = true } },
        },
        -- THE ONE STATE THE BAND CANNOT REACH, and it needs cap's own readable latch. With no
        -- Wild Imp at all there is no aura, so the client hides the whole button and every sink
        -- on it draws nothing. The `aura` predicate is readable and an unbound row reads
        -- UNKNOWN rather than false, so this stays dark rather than asserting the imps are
        -- gone. ⚠ THE `0` IS CAP'S OWN LITERAL (V22), and this marker's own `when` is what
        -- licenses it: `!aura(wild_imp)` MEANS zero, so the numeral asserts nothing cap did not
        -- already establish readably. Everywhere else on this row the count is the client's,
        -- out of an AuraContainer FontString cap never reads back — which is exactly why the
        -- zero could not come from there, and why it was drawn as a frozen clock glyph until
        -- 2026-08-28. The row is one grammar now: 0 → red 1-5 → gold 6+.
        { id = "implosion_no_imps",
          cue = "blocked",
          when = { { "aura", "wild_imp", negate = true } },
          badge = {
            kind = "numeral",
            value = 0,
          },
        },
        -- Rung 9's readable half GATES its sealed half, and that is the whole of this pair. The
        -- band's upper polarity is cap's positive ink — `count.rgb` is byte-identical to the
        -- `priority` and `capped` cue hues — so under V5.1 a gold numeral is cap saying `press
        -- this`. Ungated it said so in single target with To Hell and Back untalented, where
        -- rung 9 cannot fire at all and `implosion_st_only` is simultaneously ruling the row
        -- out: cap's own promotion ink on a button the priority list has closed. `when` is AND-
        -- only, so the disjunction `active_enemies>2|talent.to_hell_and_back` is two markers;
        -- the gates are written MUTUALLY EXCLUSIVE rather than as a plain OR because each
        -- corner display claims its own stack slot by declaration, so two live at once would
        -- draw two numerals at two corners. This is the AoE-toggle half. The NUMERAL, not the
        -- mark: `how many more` is exactly the live question below six, and the hatch beside it
        -- already carries `ruled out`. At six the count RECOLORS instead of clearing — same
        -- numeral, opposite polarity, no hatch, because a positive band may not wear one.
        { id = "implosion_imps_aoe",
          when = { { "aoe" } },
          display = {
            ability = "wild_imp",
            bands = {
              {
                draw = "count",
                hatch = true,
                polarity = "negative",
                threshold = 0,
              },
              {
                draw = "count",
                polarity = "positive",
                threshold = 6,
              },
            },
            kind = "sealed-count-bands",
          },
        },
        -- Rung 9's readable half GATES its sealed half, and that is the whole of this pair. The
        -- band's upper polarity is cap's positive ink — `count.rgb` is byte-identical to the
        -- `priority` and `capped` cue hues — so under V5.1 a gold numeral is cap saying `press
        -- this`. Ungated it said so in single target with To Hell and Back untalented, where
        -- rung 9 cannot fire at all and `implosion_st_only` is simultaneously ruling the row
        -- out: cap's own promotion ink on a button the priority list has closed. `when` is AND-
        -- only, so the disjunction `active_enemies>2|talent.to_hell_and_back` is two markers;
        -- the gates are written MUTUALLY EXCLUSIVE rather than as a plain OR because each
        -- corner display claims its own stack slot by declaration, so two live at once would
        -- draw two numerals at two corners. This is the To Hell and Back half: the talent makes
        -- Implosion a single-target press, so the count is live with the AoE toggle OFF. `!aoe`
        -- is what keeps it disjoint from `implosion_imps_aoe`. A refused `talent` read is
        -- UNKNOWN, and a gate reads a blind term as withheld (`Signal.Evaluate`), so this fails
        -- dark rather than painting on a build cap could not resolve.
        { id = "implosion_imps_thab",
          when = { { "aoe", negate = true }, { "talent", "to_hell_and_back" } },
          display = {
            ability = "wild_imp",
            bands = {
              {
                draw = "count",
                hatch = true,
                polarity = "negative",
                threshold = 0,
              },
              {
                draw = "count",
                polarity = "positive",
                threshold = 6,
              },
            },
            kind = "sealed-count-bands",
          },
        },
      },
    },
    -- 7 · hand_of_guldan. Two lives, one lane: both are shard spenders. The identity carries
    -- the transform with no cue, because Ruination outranks the ordinary press by one rung and
    -- both are pressed from this position. ⚠ But the two HOLDS are rung-11 facts and both carry
    -- `identity(hand_of_guldan, "base")` to say so: rung 10 (Ruination) is unconditional, so
    -- nothing the window rule knows can hold it.
    { id = "hand_of_guldan", ability = "hand_of_guldan",
      markers = {
        -- Sense.buildReads asks affordability of the LIVE id, so this is Ruination's cost —
        -- which is none — on the transformed row and three shards on the base one. One marker,
        -- both lives, correct in each.
        { id = "hog_starved",
          cue = "building",
          when = { { "affordable", "hand_of_guldan", negate = true } },
        },
        -- The catalog's only sealed band on a spender, and the mirror of the Tyrant hold:
        -- Tyrant holds ITSELF below five shards (readable); Hand of Gul'dan holds itself while
        -- Tyrant is nearly here (sealed). Gated on resource because rung 11's |soul_shard=5
        -- makes the spend unconditional at cap, and on affordability so it never lands on a
        -- starved row. ⚠ `identity(hand_of_guldan, "base")` scopes the hold to the row's BASE
        -- life. Both holds are derived from rung 11; while Ruination is armed the row displays
        -- rung 10, which is UNCONDITIONAL and ranked above rung 11 — holding it there would
        -- withhold a press the APL makes without any condition at all.
        { id = "hog_awaits_tyrant",
          cue = "blocked",
          when = {
            { "resource", "<=", 4 },
            { "affordable", "hand_of_guldan" },
            { "identity", "hand_of_guldan", "base" },
          },
          display = {
            ability = "summon_demonic_tyrant",
            kind = "sealed-cooldown-range",
            within = 5,
          },
        },
        -- The READABLE half of the same window rule (cue I): Tyrant READY at sub-five shards
        -- holds the spend — rung 11's remains>5 is false at zero remaining. Cue F covers
        -- `nearly here`; this covers `here, board not built`. ⚠ `identity(hand_of_guldan,
        -- "base")` scopes the hold to the row's BASE life. Both holds are derived from rung 11;
        -- while Ruination is armed the row displays rung 10, which is UNCONDITIONAL and ranked
        -- above rung 11 — holding it there would withhold a press the APL makes without any
        -- condition at all.
        { id = "hog_awaits_shards",
          cue = "building",
          when = {
            { "ready", "summon_demonic_tyrant" },
            { "resource", "<=", 4 },
            { "affordable", "hand_of_guldan" },
            { "identity", "hand_of_guldan", "base" },
          },
        },
      },
    },
    -- 8 · demonbolt. The pilot's row, and the pilot had the number wrong: the APL says
    -- soul_shard<4, so the overcap badge lights at FOUR and not at three.
    { id = "demonbolt", ability = "demonbolt",
      markers = {
        -- Demonbolt appears in actions.diabolist ONLY gated on buff.demonic_core.react, so with
        -- no Core there is no rung at all. This is also V11's hatch at zero Cores — the one
        -- state a sealed display can never decorate, because with no aura there is no button —
        -- and it needs no new vocabulary: a negative cue already hatches the row.
        { id = "db_awaits_core",
          cue = "noproc",
          when = { { "proc", "demonbolt", negate = true } },
        },
        { id = "db_overcap",
          cue = "overcap",
          when = { { "proc", "demonbolt" }, { "resource", ">=", 4 } },
        },
        -- The first marker in any catalog that reads ANOTHER ROW'S identity. Rung 12 puts an
        -- armed Infernal Bolt above Demonbolt, and only below three shards. ⚠ It stays
        -- READABLE-ONLY, and `db_yields_window` beside it carries the clock — the Grimoire
        -- row's shape (`grimoire_shows_dispel` + `grimoire_base_cooldown`), and the reason is
        -- that a cue is the thing that HATCHES the row. A display marker never contributes a
        -- cue (`Signal.markersOf` routes it to `verdict.gates`), so folding the display into
        -- this marker would have traded cap's readable elimination for a picture: the badge
        -- would still draw, and the red skip hatch under it would not.
        { id = "db_yields_to_infernal_bolt",
          cue = "blocked",
          when = { { "identity", "shadow_bolt", "transformed" }, { "resource", "<=", 2 } },
        },
        -- V21's THIRD SUPPLIER: cue D's badge is the armed Art's own remaining — a red radial
        -- the client drains off the aura's duration — instead of `timer_CW_50`, a picture of a
        -- clock face frozen at 50 % beside a hold whose whole content is *how long*. ⚠ ITS
        -- `when` IS CUE D's, TERM FOR TERM, and both terms are needed: the aura filter alone
        -- would paint the clock at three or more shards, where the row is not held at all. They
        -- ride `verdict.gates` and reach the container's own `Shown`; the slot's filter then
        -- scopes it to the armed Art. ⚠ NO NUMERAL, and that is a limit rather than a choice:
        -- V21's number comes from `FormatRemainingDuration` on a COOLDOWN object cap holds,
        -- while the only aura-side text sink (`SetDurationText`) emits fixed strings, never a
        -- value over remaining seconds. The arc alone is still strictly more than a still
        -- clock. ⚠ SECOND CONSUMER OF AURA ID `432794`, which is TIER-3-SOURCED and dies
        -- SILENT: a wrong id matches nothing forever and is indistinguishable from a refusal
        -- (the cast-id/aura-id trap). `ib_art_clock` already carries an `@verify-ingame` on
        -- that id; a second consumer doubles what one wrong number costs and does not clear it.
        -- @verify-ingame
        { id = "db_yields_window",
          cue = "blocked",
          when = { { "identity", "shadow_bolt", "transformed" }, { "resource", "<=", 2 } },
          display = {
            ability = "art_mother_of_chaos",
            kind = "sealed-aura-remaining",
          },
        },
        -- V18 · how many Cores, as a shape. `max = 4` is Demonic Core's REAL cap — *"Maximum 4
        -- stacks"* (`knowledge/classes/warlock/demonology/ability-inventory.md:555`, Tier 1) —
        -- and SetValue clamps, so the fired state is always the complete shape. ⚠ THE WHOLE-BAR
        -- RED FLIP AT FOUR IS AUTHORED PAST THE PRIORITY LIST, and that is stated rather than
        -- implied. No `actions.diabolist` rung reads Demonic Core at a HIGH threshold: rung 1
        -- reads `buff.demonic_core.stack<=1` (Power Siphon, the LOW direction) and rungs 13 and
        -- 14 read `buff.demonic_core.react`, a boolean. What the flip says is the Tier-1 game
        -- fact the list leaves unsaid — at four stacks the next proc is lost. It is a true
        -- NEGATIVE statement beside cue B's, not a second reading of it: cue B fires on four
        -- SOUL SHARDS, the flip on four DEMONIC CORES. Two costs, both real; the elimination
        -- walk still names the button. The flip itself is V18's, unconditional and declared in
        -- the shelf — a catalog names no pixels and carries no switch for it.
        { id = "db_core_charge",
          display = {
            ability = "demonic_core",
            kind = "sealed-count-bar",
            max = 4,
          },
        },
        -- V19 · Doom's pandemic window, on the button that applies it. cap authors NO
        -- threshold: the client computes GetRefreshExtendedDuration - GetAuraBaseDuration per
        -- spell. GATED on the talent, and this is the readable-gate seam: without Doom talented
        -- the fact does not exist, and a display armed for it would sit dark forever with no
        -- way to tell that from a client refusal.
        { id = "db_doom_window",
          when = { { "talent", "doom" } },
          display = {
            ability = "doom",
            kind = "sealed-pandemic",
          },
        },
        -- V20 · the Core's remaining lifetime as a thin bar directly above the charge bar. The
        -- edge carries quantity, not polarity. No threshold anywhere.
        { id = "db_core_clock",
          display = {
            ability = "demonic_core",
            kind = "sealed-proc-bar",
          },
        },
      },
    },
    -- 9 · shadow_bolt. Default membership (ready-self): a filler is always a scan candidate.
    -- The row changed KIND is said by the icon itself; the ordering correction lives on
    -- Demonbolt, which is the row that has to move. Nothing here is load-bearing for visibility
    -- — Shadow Bolt has no cooldown, so `ready` never goes false. ⚠ AND NO `alt` ON THE
    -- ABILITY, WHICH IS ALSO AUTHORED — checked in the code 2026-08-27 rather than assumed,
    -- because this entry cites BOTH the Shadow Bolt rung (`diabolist` 15) and the Infernal Bolt
    -- rung (`diabolist` 16) while the ability declares one id, 686, with no `alt`. `alt` exists
    -- for a DIFFERENT ROW, never for an override on this one — so Havoc's base-only note and
    -- Retribution's four `alt` declarations are not rival conventions but the two halves of one
    -- rule. `Bind.buildRow` sets `base = info.spellID` and puts it in `row.spellIDs`
    -- unconditionally, beside the override, the tooltip id and the live id, and
    -- `Catalog.findRow` matches ANY member; so cooldownID 34990 answers to 686 whether the row
    -- is wearing Shadow Bolt or Infernal Bolt, and the base id binds in both lives. The `alt`
    -- cases are the other shape: Templar Strike, Hammer of Wrath and this catalog's own
    -- `grimoire` choice node each carry their OWN `info.spellID`, so a declared base alone
    -- would find nothing. Infernal Bolt has no Essential row of its own in any set (Category-2
    -- TrackedBuff, OrderIndex 58/59 — `catalog.md`'s row-set table), so an `alt` of 433891
    -- would match nothing today and, if a TrackedBuff row for it were ever laid out, would bind
    -- the WRONG row. The same reading covers Ruination riding Hand of Gul'dan.
    { id = "shadow_bolt", ability = "shadow_bolt",
      markers = {
        -- V20 · how long the armed Art — and so the Infernal Bolt on this row — has left,
        -- drained by the client. The slot filters to the ART aura, so the bar exists exactly
        -- while the transform does: no identity gate needed, the visibility IS the gate. The
        -- aura id is Tier-3-sourced and unflown.
        { id = "ib_art_clock",
          display = {
            ability = "art_mother_of_chaos",
            kind = "sealed-proc-bar",
          },
        },
      },
    },
  },
}
