-- Devourer.lua — GENERATED from specs/devourer/catalog.json. Do not edit this file.
--   uv run python -m wowkb.capart export catalog devourer
-- Data only: the validator is Catalog.lua and the reasoning is catalog.md.
-- CANONICAL, hand-edited. Generates CombatAssistPlus/Catalogs/Devourer.lua via `wowkb.capart
-- export catalog devourer`, and the per-ability state table the preview draws. The Void-Scarred
-- RANGED roster (`!talent.the_hunt`); the melee branch is a three-state machine and is a
-- separate document, and Annihilator is a separate catalog. Every `apl` citation counts rungs
-- within `actions.voidscarred_ranged`, where `voidblade` is 1 — this spec has no shared body,
-- so a rung number is meaningless across branches. `hero = 126` is Void-Scarred's TraitSubTree
-- id `[T1: TraitSubTree @ 12.1.0.69214, TraitTreeID 854]`, the same table Fel-Scarred (34) and
-- Aldrachi Reaver (35) come from; Annihilator is 124 and correctly gets nothing. No `power`
-- field: Fury is a secret primary on Demon Hunter, exactly as on Havoc, so the `resource`
-- predicate can never be used here — the one Fury fact this catalog carries reaches the client
-- as a graded curve and is never compared in Lua. Base spell ids only: Bind unions
-- base/override/tooltip/live into the row, so none of the three identity chains needs a
-- hardcoded override id.
local ADDON, ns = ...

ns.Catalog.Register{
  spec = 1480,
  hero = 126,
  name = "Devourer / Void-Scarred",

  abilities = {
    -- ⚠ `1217605` is the `CooldownSetSpell` id, which is what a Cooldown Manager row is keyed
    -- on. `ability-inventory.tsv`'s `471306` is the `TraitNodeEntry` id; they are not a
    -- disagreement to reconcile. Inside the form this row's face is COLLAPSING STAR (`1221167`
    -- / `1221150`), which has no `CooldownSetSpell` row of its own in any set — an override
    -- borrows the row of the spell it replaces, and this is the third of the spec's three R7
    -- chains. Measured in game 2026-08-27.
    { id = "void_metamorphosis", spell = 1217605 },
    -- One button, three faces: Reap, Cull (in the form) and Eradicate (upgraded). Its APL gate
    -- is `action.reap.souls_consumed>=4` — fragments lying on the GROUND, which is a count of
    -- world objects rather than player state and has no API in any route (`fact-
    -- classification.md` §4.3). The row is directed by readiness alone.
    { id = "reap", spell = 1226019 },
    { id = "void_ray", spell = 473728 },
    { id = "soul_immolation", spell = 1241937 },
    -- The three-deep chain: Voidblade → Hungering Slash `1239123` (a 6 s replacement, out of
    -- the form) → Pierce the Veil `1245483` / Reaper's Toll `1245470` (the in-form Voidsurge
    -- casts). Authored LAST in the Essential order and not first: rung 1 is the branch's only
    -- out-of-Meta Voidblade line and fires in one narrow state, so a leftmost Voidblade would
    -- stop the scan on every build global.
    { id = "voidblade", spell = 1245412 },
    -- In the UTILITY viewer. cap binds it — `Bind.lua` covers all four viewers — so it is
    -- skinned and hatched, but `Anchor.lua` re-anchors Essential only, so it takes no position
    -- in the ordered scan. Its only rung is `buff.voidstep.up`, and Voidstep `1223157` is a
    -- Tier-1 registered spell-activation overlay on this spell: Blizzard already glows it,
    -- which is why this row wears no cue of cap's.
    { id = "vengeful_retreat", spell = 198793 },
    -- The branch's most-pressed button and the only press in it with NO Cooldown Manager frame
    -- in any category — not Essential, not Utility, not a tracked buff. It is therefore V12's
    -- standing virtual row. Inside the form its face is DEVOUR `1217610`; simc implements
    -- `devour_t : public consume_base_t` with `cooldown = p->cooldown.consume`, one cooldown
    -- object shared by both, so rungs 14 and 15 are one button. ⚠ cap cannot declare that
    -- transform: `Catalog.Check` refuses any subject predicate naming a virtual ability,
    -- because the read would be UNKNOWN for life. The face is resolved on the DRAW instead, by
    -- `Panel.Face`.
    { id = "consume", spell = 473662 },
    -- The SOUL BANK, and it is an aura rather than a power: Demon Hunter has exactly one row in
    -- `PowerType.csv`, FURY (17), and there is no soul-fragment power type at all `[T1 @
    -- 12.1.0.69214]`. Aura cap 50 `[T1: SpellAuraOptions.CumulativeAura]`. An aura-family
    -- subject: it never enters Signal and cap never learns its value — it exists so a sealed
    -- display can name it.
    { id = "void_metamorphosis_stack", spell = 1225789, family = "auras" },
    -- The in-window harvest counter. Every 30 grants a Collapsing Star; the counter itself caps
    -- at 40 `[T1: SpellAuraOptions.CumulativeAura @ 12.1.0.69214]`. ⚠ The KB previously
    -- recorded a max of 30, conflating the GRANT threshold with the CAP — which is what makes
    -- rung 5's `stack>=35` reachable rather than dead code.
    { id = "collapsing_star_stacking", spell = 1227702, family = "auras" },
  },

  -- Node + entry from knowledge/classes/demon-hunter/devourer/talents.json @ 12.1. `spell` is
  -- documentation only — nothing resolves through it, and Eradicate's `1226033` is the TALENT
  -- while `1239524` is the buff the upgrade puts up. ⚠ `devourers_bite` (node 110167 / entry
  -- 136692) is DELIBERATELY not declared: it gates rung 1, and rung 1 is authored as no cue at
  -- all (misordering 2), so a talent nothing reads would be a declaration with no consumer.
  talents = {
    { id = "eradicate", node = 107345, entry = 132287, spell = 1226033 },
    { id = "soul_glutton", node = 108123, entry = 134331, spell = 1247534 },
  },

  -- Entry order IS the authored priority. The first five are the Essential line `Anchor.lua`
  -- re-anchors, in cap's own order rather than Blizzard's `OrderIndex`; then the Utility row,
  -- which `Anchor.lua` does not touch and which therefore has no position in the ordered scan;
  -- then the standing virtual row, which is the terminus. ⚠ `Catalog.OrderCheck` compares this
  -- against the client's layoutIndex and will report the Utility row as out of order on most
  -- layouts — read its verdict as *the saved layout disagrees*, never as *the row on screen
  -- disagrees*.
  entries = {
    -- 1 · void_metamorphosis. ONE ROW WITH TWO JOBS, TWO COUNTS AND TWO RUNGS, selected by the
    -- identity spine and by nothing cap computes. Out of the form it is Void Metamorphosis at
    -- rung 2, gated on a soul bank cap may never read; inside the form it is Collapsing Star at
    -- rung 5 (single target) or rung 9 (AoE). Both counts are sealed and both reach the player
    -- as V16/V17 bands the CLIENT evaluates. ⚠ THREE corner displays are declared here and at
    -- most one ever draws — `CORNER_DISPLAYS` claims a stack slot per marker BY DECLARATION,
    -- not by whether the marker arms, so this row cedes three steps of the badge stack and
    -- leaves two of them permanently blank. That is the stated cost of authoring the bank fork
    -- honestly: the transform threshold is `talent(soul_glutton) ? 35 : 50`, a readable
    -- selection between two authored thresholds, and one table cannot hold both. Demonology's
    -- Implosion is the shipped precedent for the shape.
    { id = "void_metamorphosis", ability = "void_metamorphosis",
      markers = {
        -- Cue C, the *Soul Glutton* half. V17's complement: the marks draw BELOW the threshold
        -- and the band above clears them, so the row is ruled out until the bank reaches the
        -- number the catalog named and goes clean at it. The numeral is the readout the design
        -- argument is about — `how many more` is exactly the live question here — and the hatch
        -- beside it is what makes the elimination genuine. ⚠ It is gated on
        -- `identity(void_metamorphosis, "base")`: inside the form the row is Collapsing Star,
        -- the bank is expired (`sc_demon_hunter.cpp:9179`) and cannot refill, and this count
        -- would be drawing a number about a button that is not on screen.
        { id = "meta_bank_glutton",
          when = { { "identity", "void_metamorphosis", "base" }, { "talent", "soul_glutton" } },
          display = {
            ability = "void_metamorphosis_stack",
            bands = {
              {
                draw = "count",
                hatch = true,
                polarity = "negative",
                threshold = 0,
              },
              {
                draw = "none",
                threshold = 35,
              },
            },
            kind = "sealed-count-bands",
          },
        },
        -- Cue C, the no-*Soul Glutton* half — 50 fragments, which is also the aura's own cap.
        -- The two halves are written as MUTUALLY EXCLUSIVE `when` gates on one readable talent
        -- read rather than as one table carrying both numbers, because a single authored
        -- threshold is wrong on one build or the other in a direction that matters: 35 on a
        -- deep-bank build clears a row the game will not cast, and 50 on a *Soul Glutton* build
        -- HATCHES a row the game will — eliminating the correct press, which is the failure
        -- class Protection's `as_guidance_capped` was. ⚠ A refused `talent` read is UNKNOWN and
        -- a gate reads a blind term as withheld (`Signal.Evaluate`), so on a build cap cannot
        -- resolve NEITHER half paints and the row is an ordinary candidate rather than a
        -- wrongly-hatched one.
        { id = "meta_bank_deep",
          when = {
            { "identity", "void_metamorphosis", "base" },
            { "talent", "soul_glutton", negate = true },
          },
          display = {
            ability = "void_metamorphosis_stack",
            bands = {
              {
                draw = "count",
                hatch = true,
                polarity = "negative",
                threshold = 0,
              },
              {
                draw = "none",
                threshold = 50,
              },
            },
            kind = "sealed-count-bands",
          },
        },
        -- Cue C's other count: the in-window harvest, on the same row, selected by identity.
        -- The threshold is the GRANT at 30 and not rung 5's 35, and that choice is authored
        -- rather than incidental. Rung 9 (AoE) carries no counter term at all, so any granted
        -- Star is pressable there; rung 5 (single target) wants 35. A band at 30 is one band
        -- early in single target — documented misordering 1, the Star is early rather than
        -- wasted — while a band at 35 would HATCH a row rung 9 wants pressed, which is the
        -- eliminate-the-correct-press direction. Early beats absent. ⚠ It carries no `aoe` term
        -- precisely because the safe direction is the same in both modes.
        { id = "star_counter",
          when = { { "identity", "void_metamorphosis", "transformed" } },
          display = {
            ability = "collapsing_star_stacking",
            bands = {
              {
                draw = "count",
                hatch = true,
                polarity = "negative",
                threshold = 0,
              },
              {
                draw = "none",
                threshold = 30,
              },
            },
            kind = "sealed-count-bands",
          },
        },
        -- Cue D. Rung 2 holds the transform at 2+ targets while the Eradicate upgrade is not
        -- banked; cap draws `!proc(reap) & talent(eradicate) & aoe`. ⚠ IT IS A SOUND SLICE OF
        -- THE RUNG AND NOT THE RUNG. Eradicate `1239524` and Moment of Craving `1238495` both
        -- icon-highlight Reap / Cull / Eradicate, so `proc(reap)` is their OR and this marker
        -- encodes `!eradicate ∧ !moment_of_craving` where rung 2 negates `!eradicate` alone. It
        -- therefore holds STRICTLY LESS OFTEN than the rung would: `!proc ⇒ !eradicate.up`, so
        -- the badge can never fire in a state where the APL would cast, and what it loses is
        -- the hold where Moment of Craving is up with Eradicate down. Missing a hold is the
        -- safe direction; eliminating a press is not. `identity(void_metamorphosis, "base")`
        -- scopes it out of the form, where rung 2 is structurally dead — entering the form
        -- expires the bank with no way to refill it.
        { id = "meta_eradicate_hold",
          cue = "blocked",
          when = {
            { "identity", "void_metamorphosis", "base" },
            { "aoe" },
            { "talent", "eradicate" },
            { "proc", "reap", negate = true },
          },
        },
        -- The AoE half of the position-1 correction. In AoE Collapsing Star is rung 9, BELOW
        -- Void Ray's rung 8, and the face is the leftmost icon on the line — so without this
        -- the scan takes it a rung early whenever Void Ray is up. `ready(void_ray)` is
        -- necessary but NOT sufficient, and the fourth term is why. ⚠ Rung 8 is
        -- `!buff.eradicate.up|!buff.moment_of_craving.up|set_bonus...4pc`, so with BOTH procs
        -- banked and no 4-piece the APL skips Void Ray and rung 9 IS the press — and a hold on
        -- readiness alone would badge the correct press `blocked`, which is the one direction
        -- this catalog refuses (cue D is argued on exactly the opposite standard). cap cannot
        -- read that AND: the overlay channel gives Eradicate and Moment of Craving ONE row, so
        -- `proc(reap)` is their OR and rung 8 needs their AND (`fact-classification.md` §4.2,
        -- documented misordering 4). `!proc(reap)` is the strongest thing cap can say that is
        -- still SAFE — neither proc up implies `!eradicate`, which implies rung 8 fires. The
        -- cost is that with exactly ONE proc up the hold is missing and Collapsing Star over-
        -- ranks by one rung, which is a missed hold and not a wrong press. In single target the
        -- hold is absent because rung 5 sits ABOVE rung 8 and position 1 is right. ⚠ The
        -- single-target/AoE split rests on cap's OWN `/cap aoe` toggle, not on a game read of
        -- enemy count.
        { id = "star_yields_to_void_ray",
          cue = "blocked",
          when = {
            { "identity", "void_metamorphosis", "transformed" },
            { "aoe" },
            { "ready", "void_ray" },
            { "proc", "reap", negate = true },
          },
        },
      },
    },
    -- 2 · reap. One button wearing three faces, and the face changes what the button is FOR:
    -- Eradicate is a 25 yd frontal cone you aim, Cull is the in-window harvest, Reap is the
    -- builder. No cue — Blizzard's own overlay glow already says `upgraded`, which is most of
    -- what a hint here would have said, and the rung's real gate is fragments on the ground,
    -- which no route reads.
    { id = "reap", ability = "reap",
    },
    -- 3 · void_ray. The one spender in the branch with a real cost — 100 Fury, secret — and the
    -- Cooldown Manager shows it castable when you cannot pay, which is the exact failure R1
    -- exists for. It is also the button that CREATES the Eradicate upgrade and the Moment of
    -- Craving reset, so a dropped channel costs two things the damage number does not show.
    { id = "void_ray", ability = "void_ray",
      markers = {
        -- Havoc's cue A verbatim. ⚠ Rung 8's own hold is NOT authored, and it does not resolve
        -- by measuring: `!buff.eradicate.up|!buff.moment_of_craving.up|4pc` needs the AND of
        -- two auras that share one overlay channel, so `proc(reap)` is their OR and the
        -- necessary condition is authorable while the sufficient one is not. A badge on the
        -- necessary condition would fire in states where the APL casts.
        { id = "void_ray_starved",
          cue = "starved",
          when = { { "affordable", "void_ray", negate = true } },
        },
      },
    },
    -- 4 · soul_immolation. INSIDE THE FORM THIS IS NOT A MAINTENANCE PRESS — it is the thing
    -- that keeps the form alive. Fury drains continuously and accelerating; at zero the window
    -- ends; Soul Immolation returns 30 Fury (+12 with Singed Spirit) over 5 s on a ~1 min
    -- cooldown, so spending it early means not having it when the window is ending. `ready` is
    -- a good proxy for rung 13's `active_dot=0` half: a 5 s effect on a ~60 s cooldown is
    -- absent whenever the button is up.
    { id = "soul_immolation", ability = "soul_immolation",
      markers = {
        -- Cue B, and the readable gate beside the sealed curve is the shape
        -- `when`-with-`display` exists for: `identity(void_metamorphosis, "transformed")` is
        -- *am I in the form*, read off ANOTHER row's identity, and it decides whether the
        -- client may paint at all. Void Metamorphosis's row is the unambiguous subject for that
        -- question — Reap's identity also flips out of the form, when Eradicate is banked. The
        -- break point is rung 13's `fury < void_metamorphosis_base_drain_ps`, authored as an
        -- ABSOLUTE threshold because the term is one: cap divides by the client's own max and
        -- never learns which side the secret fell on. ⚠ THE NUMBER IS FITTED, NOT MEASURED —
        -- ≈16.4 Fury/s at window start off simc's curve, RISING through the window, and a
        -- quarter faster again on a *Soul Glutton* build, so a static threshold under-fires
        -- late in a window, which is when it matters most. 17 is the round number one tick of
        -- the opening drain sits under.
        { id = "soul_immolation_drain_save",
          cue = "blocked",
          when = { { "identity", "void_metamorphosis", "transformed" } },
          display = {
            kind = "sealed-power-percent",
            power = "Fury",
            threshold = 17,
          },
        },
      },
    },
    -- 5 · voidblade. Two different problems on one icon, and NO cue for either. Outside the
    -- form rung 1 says *spend the last global before you transform*, because with Devourer's
    -- Bite the cast lands a stacking +12 % damage-taken debuff you want ON the window — and its
    -- gate is the bank at max, which is sealed and has no readable surrogate today. Inside the
    -- form the row is Pierce the Veil or Reaper's Toll, the once-per-window Voidsurge casts,
    -- whose gates are simc placeholder buffs with no game aura at all. Both holds are open
    -- facts; both are documented misorderings rather than silent gaps.
    { id = "voidblade", ability = "voidblade",
    },
    -- 6 · vengeful_retreat. ⚠ THE ONE ROW IN THIS CATALOG THAT IS NOT IN THE ANCHORED LINE. It
    -- lives in the Utility viewer, and `Anchor.lua` re-anchors Essential only — so cap skins
    -- it, hatches it and gives it the scan edge, but where it sits on screen is Edit Mode's
    -- business and no left-to-right position here is a claim about pixels. It carries no cue on
    -- merit rather than by deferral: its only rung is `buff.voidstep.up`, and Voidstep is a
    -- Tier-1 registered spell-activation overlay on this exact spell, so Blizzard already glows
    -- it — cap does not draw a second mark for a fact the client marks.
    { id = "vengeful_retreat", ability = "vengeful_retreat",
    },
    -- 7 · consume. V12's standing virtual row, and the terminus of the elimination walk. Tier 1
    -- on every leg of the premise: cooldown `0`, no `SpellPower` row for `473662` at
    -- 12.1.0.69214 so no resource cost, no aura gate, castable while moving — its availability
    -- is a constant, which is exactly V12's test for `standing`. It therefore sits at the RIGHT
    -- end of the panel, draws clear at all times and carries no readable gate: its position
    -- already encodes its priority. ⚠ It is not wallpaper — it is what makes elimination total
    -- on this spec. Without it there are ordinary states (spender unaffordable, everything else
    -- swiped) where the sweep ends in silence and the answer is reachable only from memory. ⚠
    -- Nothing is authored for the Season 2 2-piece promotion to rung 4: Soulburst `1297433` is
    -- a registered overlay on Consume AND Devour, so the client already glows it.
    { id = "consume", ability = "consume", virtual = "standing",
    },
  },
}
