-- Protection.lua — GENERATED from specs/protection/catalog.json. Do not edit this file.
--   uv run python -m wowkb.capart export catalog protection
-- Data only: the validator is Catalog.lua and the reasoning is catalog.md.
-- CANONICAL, hand-edited. Generates CombatAssistPlus/Catalogs/Protection.lua via `wowkb.capart
-- export catalog protection`, and the per-ability state table the preview draws. The Lightsmith
-- roster; Templar is a separate catalog authored later, not a second overlay bolted on here. ⚠
-- `hero` is deliberately unset: the Paladin hero sub-tree ids have not been read from a live
-- client, and inventing one would silently bind nothing. Unset means "any hero tree" — and
-- unlike Retribution, whose roster was spec-wide, THIS roster is Lightsmith-specific, so a
-- Templar Protection Paladin gets a catalog built around an armament row their build does not
-- have. That is real exposure, not a formality. ⚠ NO `power` field, measured rather than
-- omitted: the 12.1 Protection priority list carries no `holy_power` term of any kind. "Paladin
-- ⇒ declare HolyPower" is exactly the inference the second Paladin catalog invites, and it is
-- wrong. ⚠ NO row declares `charged`, and four of them would want to — this repo carries no
-- Tier-1 charge count for Holy Armaments, Shield of the Righteous or Crusader Strike, and
-- Judgment's second charge is talent-conditional. The consequence is that `capped` has no
-- subject anywhere in this catalog. Base spell ids only: Bind unions base/override/tooltip/live
-- into the row, so neither the Sacred Weapon nor the Hammer of Wrath transform needs a
-- hardcoded override id.
local ADDON, ns = ...

ns.Catalog.Register{
  spec = 66,
  name = "Protection / Lightsmith",

  abilities = {
    { id = "avenging_wrath", spell = 31884 },
    { id = "divine_toll", spell = 375576 },
    { id = "shield_of_the_righteous", spell = 53600 },
    { id = "holy_armaments", spell = 432459 },
    { id = "avengers_shield", spell = 31935 },
    { id = "consecration", spell = 26573 },
    { id = "judgment", spell = 275779 },
    { id = "crusader_strike", spell = 35395, alt = { 53595, 204019 } },
    { id = "word_of_glory", spell = 85673 },
    { id = "vanguard", spell = 1267203, family = "auras" },
    { id = "blessed_assurance", spell = 433015, family = "auras" },
    { id = "divine_guidance", spell = 433106, family = "auras" },
    { id = "shining_light", spell = 321136, family = "auras" },
  },

  -- Node + entry from `knowledge/classes/paladin/protection/ability-inventory.tsv` @ 12.1. ⚠
  -- `divine_guidance` and `blessed_assurance` SHARE node 95235, and that is the fact rather
  -- than a typo: they are the Lightsmith choice node at 8,11, so exactly one of them exists on
  -- any build and the other is dead. Two markers are gated on it in opposite directions. ⚠ The
  -- key `divine_guidance` appears in BOTH families and that is legal — `Catalog.Check` keys
  -- `abilities` and `talents` in separate tables and the `talent` predicate resolves only the
  -- second. The aura is the stacking buff; the talent is whether the buff can exist at all.
  talents = {
    { id = "righteous_protector", node = 81477, entry = 102440, spell = 204074 },
    { id = "divine_guidance", node = 95235, entry = 117884, spell = 433106 },
    { id = "blessed_assurance", node = 95235, entry = 117883, spell = 433015 },
  },

  -- Entry order IS the authored priority, and it is the flattened `actions.default` — one list,
  -- no sub-lists and no hero fork, with four rows whose rungs straddle another row's.
  -- `Catalog.OrderCheck` reports when the player's Cooldown Manager disagrees with it.
  entries = {
    -- 1 · avenging_wrath. Rung 5. A PLACED cooldown: its value is set by what lands inside it,
    -- and Divine Toll's clock is the whole of that. Sealed, so the hold is a band.
    { id = "avenging_wrath", ability = "avenging_wrath",
      markers = {
        { id = "aw_awaits_toll",
          cue = "blocked",
          when = { { "ready", "avenging_wrath" } },
          display = {
            ability = "divine_toll",
            beyond = 10,
            kind = "sealed-cooldown-range",
          },
        },
      },
    },
    -- 2 · divine_toll. Rung 7, the spec's largest Holy Power injection, and it belongs inside
    -- Wings. ⚠ The rung has two disjuncts and only the second is authorable: the first is
    -- `buff.avenging_wrath.up`, and whether a Category-3 (TrackedBar) row raises the `aura`
    -- latch's alert edges is UNMEASURED. A latch on an unmeasured edge is a hold that may never
    -- release, so it is not authored.
    { id = "divine_toll", ability = "divine_toll",
      markers = {
        { id = "dt_awaits_wrath",
          cue = "blocked",
          when = { { "ready", "divine_toll" }, { "talent", "righteous_protector", negate = true } },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 30,
          },
        },
      },
    },
    -- 3 · shield_of_the_righteous. Rung 9, the spender and the active mitigation. ⚠ Rung 9 is
    -- UNCONDITIONAL on Lightsmith by derivation rather than by reading: every term in its
    -- condition is Templar's, so with no Hammer of Light on the build the first disjunct is
    -- trivially true. The row needs no press gate at all, which is why the spender's placement
    -- is pure position — and why its one marker is about affordability instead.
    { id = "shield_of_the_righteous", ability = "shield_of_the_righteous",
      scan_when = { { { "affordable", "shield_of_the_righteous" } } },
      markers = {
        { id = "sotr_starved",
          cue = "starved",
          when = { { "affordable", "shield_of_the_righteous", negate = true } },
        },
      },
    },
    -- 4 · holy_armaments. Rungs 10 / 14, 23. One button, two jobs.
    { id = "holy_armaments", ability = "holy_armaments",
      markers = {
        { id = "ha_banks_bulwark",
          cue = "blocked",
          when = { { "identity", "holy_armaments", "base" }, { "ready", "holy_armaments" } },
          display = {
            ability = "avenging_wrath",
            beyond = 5,
            kind = "sealed-cooldown-range",
          },
        },
      },
    },
    -- 5 · avengers_shield. Rungs 13 and 18. It FEELS like the top of the rotation and rung 18
    -- is the low unconditional one, with three rungs between it and rung 13. Only Glory of the
    -- Vanguard genuinely puts it first — which is why the Vanguard term is a READABLE GATE on a
    -- sealed display, the `when`-beside-`display` shape. Without it the hatch would rule out
    -- the row in the one state rung 13 puts it first.
    { id = "avengers_shield", ability = "avengers_shield",
      markers = {
        { id = "as_awaits_hammer",
          cue = "blocked",
          when = {
            { "identity", "judgment", "transformed" },
            { "ready", "judgment" },
            { "aura", "vanguard", negate = true },
            { "ready", "avengers_shield" },
          },
        },
        { id = "as_guidance_capped",
          when = {
            { "aura", "vanguard", negate = true },
            { "talent", "divine_guidance" },
            { "ready", "avengers_shield" },
          },
          display = {
            ability = "divine_guidance",
            bands = {
              {
                draw = "none",
                threshold = 0,
              },
              {
                draw = "mark",
                hatch = true,
                polarity = "negative",
                threshold = 5,
              },
            },
            kind = "sealed-count-bands",
          },
        },
      },
    },
    -- 6 · consecration. Rungs 15, 19, 24 and 29. ⚠ Rungs 19 and 24 are not modelled:
    -- `!consecration.up` reads a Category-3 (TrackedBar) row, the same unmeasured alert-edge
    -- question as Avenging Wrath's buff.
    { id = "consecration", ability = "consecration",
      markers = {
        { id = "cons_awaits_hammer",
          when = {
            { "identity", "judgment", "transformed" },
            { "ready", "judgment" },
            { "talent", "divine_guidance" },
            { "ready", "consecration" },
          },
          display = {
            ability = "divine_guidance",
            bands = {
              {
                draw = "mark",
                hatch = true,
                polarity = "negative",
                threshold = 0,
              },
              {
                draw = "none",
                threshold = 5,
              },
            },
            kind = "sealed-count-bands",
          },
        },
      },
    },
    -- 7 · judgment. Rungs 17, 22 / 16. ⚠ Rung 17 is not authored — the second-charge dump, and
    -- `charged` is undeclarable on this spec.
    { id = "judgment", ability = "judgment",
      markers = {
        { id = "judgment_awaits_assurance",
          cue = "blocked",
          when = {
            { "aura", "blessed_assurance" },
            { "talent", "blessed_assurance" },
            { "identity", "judgment", "base" },
            { "ready", "judgment" },
          },
        },
      },
    },
    -- 8 · crusader_strike. Rungs 20, 21 / 25, 26. ⚠ Its Blessed Assurance promotion is
    -- expressed on Judgment (cue F), not here: this row does not change KIND under the buff,
    -- and a rank change within one kind is what the left-to-right scan already carries.
    { id = "crusader_strike", ability = "crusader_strike",
    },
    -- 9 · word_of_glory. Rung 28. A Holy Power heal competing with the active mitigation for
    -- the same three Holy Power.
    { id = "word_of_glory", ability = "word_of_glory",
      markers = {
        { id = "wog_awaits_shining_light",
          cue = "blocked",
          when = { { "aura", "shining_light", negate = true } },
        },
      },
    },
  },
}
