-- Retribution.lua — GENERATED from specs/retribution/catalog.json. Do not edit this file.
--   uv run python -m wowkb.capart export catalog retribution
-- Data only: the validator is Catalog.lua and the reasoning is catalog.md.
-- CANONICAL, hand-edited. Generates CombatAssistPlus/Catalogs/Retribution.lua via `wowkb.capart
-- export catalog retribution`, and the per-ability state table the preview draws. The Templar
-- roster. `power = "HolyPower"`: Holy Power is NEVER-SECRET, so unlike Havoc's Fury the
-- `resource` predicate is usable and this is the first catalog where a resource does ordering
-- work. ⚠ `hero` is deliberately unset: the Templar sub-tree id has not been read from a live
-- client, and inventing one would silently bind nothing. Unset means "any hero tree", which on
-- Herald of the Sun offers a Templar-authored priority — acceptable while this addon has one
-- Templar user, and the one line to tighten once the id is known. ⚠ The Expurgation row is
-- `383346`, the debuff that LANDS, not `383344`, the passive talent node — confirmed in client
-- 2026-08-19 by icon. It binds only if the player has added Expurgation to Tracked Buffs; if
-- not, `aura:expurgation` reads UNKNOWN and its marker stays DARK rather than reading as "the
-- DoT is down".
local ADDON, ns = ...

ns.Catalog.Register{
  spec = 70,
  name = "Retribution / Templar",
  power = "HolyPower",

  abilities = {
    { id = "execution_sentence", spell = 343527 },
    { id = "avenging_wrath", spell = 31884 },
    { id = "wake_of_ashes", spell = 255937, alt = { 427453 } },
    { id = "divine_toll", spell = 375576 },
    { id = "templars_verdict", spell = 85256, alt = { 383328 } },
    { id = "divine_storm", spell = 53385 },
    { id = "blade_of_justice", spell = 184575 },
    { id = "judgment", spell = 20271, alt = { 24275 } },
    { id = "crusader_strike", spell = 35395, alt = { 407480 } },
    { id = "expurgation", spell = 383346, family = "auras", unit = "target" },
  },

  -- Node + entry from `knowledge/classes/paladin/retribution/ability-inventory.tsv`. ⚠
  -- `execution_sentence` is declared as a TALENT as well as an ability because `generators` 3's
  -- first disjunct is `!talent.execution_sentence` — the rung is unconditional on a build
  -- without it, so the hold that yields to it must ask whether it is TAKEN, not only whether it
  -- is ready.
  talents = {
    { id = "holy_flames", node = 109371, entry = 115438, spell = 406545 },
    { id = "radiant_glory", node = 81549, entry = 102525, spell = 458359 },
    { id = "execution_sentence", node = 109373, entry = 115435, spell = 343527 },
  },

  -- Entry order IS the authored priority; `Catalog.OrderCheck` reports when the player's
  -- Cooldown Manager disagrees with it.  ⚠ THE RUNG-CITATION CONVENTION, stated so nobody
  -- "fixes" it back. A state's `apl` names the rung that carries the FACT the state is about,
  -- not the rung that presses this row. So `dt_overcap` cites `generators 1` (where
  -- `holy_power=5` lives), not `generators 4` (Divine Toll's own rung), and `tv_awaits_blade`
  -- cites `generators 5` (the Blade of Justice proc rung that outranks it). A `_clear` state
  -- has no such fact and therefore cites the row's own rung. `finishers 1` is the `ds_castable`
  -- VARIABLE rung and citing it is deliberate, not sloppy: a `variable` line is where the fact
  -- is defined and the rungs below merely test it. For a COMBINED state the tie is broken by
  -- the list itself: it cites the EARLIEST of its markers' rungs — the one the priority list
  -- reaches first, and so the one that actually eliminates this row. That is always the
  -- citation of one of its single-marker siblings, never a third number. Worked: `dt_overcap`
  -- cites `generators 1` over `generators 4`; `ds_aoe_only_and_blade` and `tv_awaits_blade`
  -- cite `generators 5` over `finishers 1`/`4`, because their `resource <= 4` term means
  -- `generators` 1's conditional call into `finishers` cannot have fired; `tv_empyrean_power`
  -- and `tv_divine_storm_aoe` cite `finishers 1`, which is where both their markers live. ⚠ The
  -- four states this example used to name were marker-PAIR states, deleted 2026-08-29 into
  -- `overlaps`; the citation convention is unchanged and is shown here on the single-marker
  -- states that survived. This is DISPLAY-ONLY and deliberately UNGATED — `catalog_gate_holds`
  -- and `catalog_gate_display_provenance` read these citations for their own purposes, and a
  -- gate on the convention itself would freeze an editorial choice.
  entries = {
    -- 1 · execution_sentence. 1. A PLACED cooldown, not a press-on-cooldown one. FOUR markers,
    -- one cue key, so the AND-only band grammar unions them into a single badge.
    { id = "execution_sentence", ability = "execution_sentence",
      markers = {
        { id = "es_awaits_wrath_ready",
          cue = "blocked",
          when = {
            { "ready", "execution_sentence" },
            { "talent", "radiant_glory", negate = true },
            { "ready", "avenging_wrath" },
          },
        },
        { id = "es_awaits_wrath",
          cue = "blocked",
          when = { { "ready", "execution_sentence" }, { "talent", "radiant_glory", negate = true } },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 15,
          },
        },
        { id = "es_awaits_wake",
          cue = "blocked",
          when = { { "ready", "execution_sentence" } },
          display = {
            ability = "wake_of_ashes",
            beyond = 1.5,
            kind = "sealed-cooldown-range",
          },
        },
        -- The SAME clause `aw_awaits_expurgation` authors one entry down —
        -- `(!talent.holy_flames|dot.expurgation.ticking)`, the last term of cooldowns 10 — and
        -- it is one marker rather than two because the APL's OR negates into a plain AND: Holy
        -- Flames talented AND the DoT absent.
        { id = "es_awaits_expurgation",
          cue = "blocked",
          when = {
            { "ready", "execution_sentence" },
            { "talent", "holy_flames" },
            { "aura", "expurgation", negate = true },
          },
        },
      },
    },
    -- 2 · avenging_wrath. 2. The window everything aligns into.
    { id = "avenging_wrath", ability = "avenging_wrath",
      markers = {
        { id = "aw_awaits_expurgation",
          cue = "blocked",
          when = {
            { "ready", "avenging_wrath" },
            { "talent", "holy_flames" },
            { "aura", "expurgation", negate = true },
          },
        },
        -- V20 · the DoT the hold above waits on, as a bar the CLIENT drains, hosted on the row
        -- whose badge depends on it. It is V20 and not V19 deliberately: V19's badge wears the
        -- FULL positive-cue treatment — promotion ring and halo — and nothing in this priority
        -- refreshes Expurgation, so "press now" is a sentence this row must not say. A bottom
        -- edge carries quantity, not verdict. ⚠ It needs NO Cooldown-Manager row for its
        -- subject: a sealed container is cap's own frame, filtered by `includeSpellIDs` and
        -- pointed with `SetUnit(plan.unit)` — which is exactly why it is worth having. The
        -- `aura` latch above goes blind when the player never enabled the Tracked Buff row; the
        -- bar does not. GATED on the talent, the same readable-gate seam Demonology's Doom
        -- window uses: without Holy Flames the fact is not part of the priority and an armed
        -- display would sit dark forever with no way to tell that from a refusal.
        { id = "aw_expurgation_clock",
          when = { { "talent", "holy_flames" } },
          display = {
            ability = "expurgation",
            kind = "sealed-proc-bar",
          },
        },
      },
    },
    -- 3 · wake_of_ashes. 3. One row, two lives, selected by identity.
    { id = "wake_of_ashes", ability = "wake_of_ashes",
      scan_when = {
        { { "identity", "wake_of_ashes", "base" }, { "ready", "wake_of_ashes" } },
        { { "identity", "wake_of_ashes", "transformed" } },
      },
      markers = {
        { id = "woa_starved",
          cue = "starved",
          when = { { "affordable", "wake_of_ashes", negate = true } },
        },
        { id = "woa_awaits_wrath",
          cue = "blocked",
          when = {
            { "identity", "wake_of_ashes", "base" },
            { "ready", "wake_of_ashes" },
            { "talent", "radiant_glory", negate = true },
          },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 6,
          },
        },
        -- The SEALED half of `generators` 3's Execution Sentence clause, and the pair is now
        -- gated CONSISTENTLY: both this and `woa_awaits_sentence_ready` carry
        -- `talent(execution_sentence)`, for the same reason and in the same words. The clause
        -- is `(!talent.execution_sentence|cooldown.execution_sentence.remains>4|target.time_to_
        -- die<10)`, so on a build WITHOUT Execution Sentence the first disjunct is TRUE and
        -- `generators` 3 is unconditional — a hold derived from that clause has no business
        -- drawing there at all. ⚠ **This was NOT harmless-by-refusal, and the difference is the
        -- point.** A `sealed-cooldown-range` binds on the CATALOG's static `spell` number
        -- (`Channel.HoldPlan` / `Channel.ArmHold`), never on whether the client knows the spell
        -- — so on an untalented build the plan built, the Step curve built, and
        -- `Overlay.armGraded` reported status **`armed`**. What kept it dark was the per-draw
        -- nil-guard in `Channel.HoldAlpha`: `C_Spell.GetSpellCooldownDuration` is
        -- `MayReturnNothing` and its sibling `C_Spell.GetSpellCooldown` is recorded as
        -- returning nil on an unknown spell (`knowledge/addon-dev/cooldown-manager.md:2065`).
        -- That is safe by accident of the client, and it printed `armed` in every capture on a
        -- build where the hold could never be right. With the talent term the marker's readable
        -- gate resolves false, `Overlay` hides the badge and reports **`gated`** — nothing
        -- failed, the row is simply not in the state that licenses the display. Safe because we
        -- said so, and it says so in the capture.
        { id = "woa_awaits_sentence",
          cue = "blocked",
          when = {
            { "identity", "wake_of_ashes", "base" },
            { "ready", "wake_of_ashes" },
            { "talent", "execution_sentence" },
          },
          display = {
            ability = "execution_sentence",
            kind = "sealed-cooldown-range",
            within = 4,
          },
        },
        -- The READABLE half of `woa_awaits_sentence`, and the sibling of
        -- `es_awaits_wrath_ready` one row to the left. `generators` 3's second clause is `(!tal
        -- ent.execution_sentence|cooldown.execution_sentence.remains>4|target.time_to_die<10)`:
        -- with Execution Sentence talented and READY the first two disjuncts are false, so the
        -- APL does not press Wake of Ashes at all — and the `within = 4` band reads NOTHING at
        -- zero remaining, exactly as the Avenging Wrath band does on row 1. ⚠ The `talent` term
        -- is load-bearing and not belt-and-braces: on a build without Execution Sentence the
        -- first disjunct is TRUE and this rung is unconditional, so an ungated hold would badge
        -- a press the APL makes freely. ⚠ ONE HONEST OVER-HOLD: `target.time_to_die<10` also
        -- satisfies the clause and cap does not model the encounter — no `fight_remains`, by
        -- product rule, the same exclusion Demonology's rung 1 records. So in the last ten
        -- seconds of a fight this holds a Wake of Ashes the APL presses. That is a MISSED
        -- PRESS, not a wrong one, which is the direction this project accepts everywhere else.
        { id = "woa_awaits_sentence_ready",
          cue = "blocked",
          when = {
            { "identity", "wake_of_ashes", "base" },
            { "ready", "wake_of_ashes" },
            { "talent", "execution_sentence" },
            { "ready", "execution_sentence" },
          },
        },
      },
    },
    -- 4 · divine_toll. 4. The one builder that genuinely must not be pressed at cap.
    { id = "divine_toll", ability = "divine_toll",
      markers = {
        { id = "dt_awaits_wrath",
          cue = "blocked",
          when = { { "ready", "divine_toll" }, { "talent", "radiant_glory", negate = true } },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 15,
          },
        },
        { id = "dt_overcap",
          cue = "overcap",
          when = { { "ready", "divine_toll" }, { "resource", ">=", 5 } },
        },
      },
    },
    -- 5 · templars_verdict. 5. The default spender, and the wrong one in three states that look
    -- identical on the icon.
    { id = "templars_verdict", ability = "templars_verdict",
      scan_when = { { { "affordable", "templars_verdict" } } },
      markers = {
        { id = "tv_starved",
          cue = "starved",
          when = { { "affordable", "templars_verdict", negate = true } },
        },
        { id = "tv_awaits_blade",
          cue = "blocked",
          when = {
            { "proc", "blade_of_justice" },
            { "ready", "blade_of_justice" },
            { "resource", "<=", 4 },
            { "affordable", "templars_verdict" },
          },
        },
        { id = "tv_divine_storm_aoe",
          cue = "st_only",
          when = {
            { "aoe" },
            { "proc", "templars_verdict", negate = true },
            { "affordable", "templars_verdict" },
          },
        },
        { id = "tv_empyrean_power",
          cue = "blocked",
          when = {
            { "proc", "divine_storm" },
            { "proc", "templars_verdict", negate = true },
            { "affordable", "templars_verdict" },
          },
        },
      },
    },
    -- 6 · divine_storm. 6. Needs no mirror of the generator hold to steer the scan — it sits
    -- RIGHT of Templar's Verdict — but carries one anyway so the two spenders can be told
    -- apart.
    { id = "divine_storm", ability = "divine_storm",
      scan_when = { { { "affordable", "divine_storm" } } },
      markers = {
        { id = "ds_starved",
          cue = "starved",
          when = { { "affordable", "divine_storm", negate = true } },
        },
        { id = "ds_aoe_only",
          cue = "aoe_only",
          when = {
            { "aoe", negate = true },
            { "proc", "divine_storm", negate = true },
            { "affordable", "divine_storm" },
          },
        },
        { id = "ds_awaits_blade",
          cue = "blocked",
          when = {
            { "proc", "blade_of_justice" },
            { "ready", "blade_of_justice" },
            { "resource", "<=", 4 },
            { "affordable", "divine_storm" },
          },
        },
      },
    },
    -- 7 · blade_of_justice. 7. ONE cue, and it is the vocabulary's second positive — worn by
    -- TWO markers, because the rung's reachability condition is a disjunction and `when` is
    -- AND-only.
    { id = "blade_of_justice", ability = "blade_of_justice",
      markers = {
        -- `resource <= 4` is the reachability term. `generators` 1 is an unconditional call
        -- into `finishers` gated on `holy_power=5&cooldown.wake_of_ashes.remains`, so rung 2 is
        -- only REACHED when that rung did not fire — which is `holy_power<=4` OR Wake of Ashes
        -- ready. `when` is AND-only (`Signal.lua`), so the OR is authored as two markers
        -- wearing the same cue: this is its left half. Same term, same reason, as
        -- `tv_awaits_blade` and `ds_awaits_blade`.
        { id = "boj_opener",
          cue = "priority",
          when = {
            { "ready", "blade_of_justice" },
            { "talent", "holy_flames" },
            { "aura", "expurgation", negate = true },
            { "resource", "<=", 4 },
          },
        },
        -- The right half of the same OR. At five Holy Power `generators` 1 still falls through
        -- whenever Wake of Ashes is READY (`cooldown.wake_of_ashes.remains` is 0, so the rung's
        -- own condition is false), and rung 2 is reached again. Two markers, one cue: the union
        -- IS the disjunction, and `Catalog.lua`'s two-positive-cues refusal is per CUE, not per
        -- marker — one badge on screen either way.
        { id = "boj_opener_woa",
          cue = "priority",
          when = {
            { "ready", "blade_of_justice" },
            { "talent", "holy_flames" },
            { "aura", "expurgation", negate = true },
            { "ready", "wake_of_ashes" },
          },
        },
      },
    },
    -- 8 · judgment. 8.
    { id = "judgment", ability = "judgment",
    },
    -- 9 · crusader_strike. 9.
    { id = "crusader_strike", ability = "crusader_strike",
    },
  },
}
