-- Retribution.lua — GENERATED from specs/retribution/catalog.json. Do not edit this file.
--   uv run python -m wowkb.capart export catalog retribution
-- Data only: the validator is Catalog.lua and the reasoning is catalog.md.
-- CANONICAL, hand-edited. Generates CombatAssistPlus/Catalogs/Retribution.lua via `wowkb.capart
-- export catalog retribution`, and the per-ability state table the preview draws. The Templar
-- roster. `power = "HolyPower"`: Holy Power is NEVER-SECRET, so unlike Havoc's Fury the
-- `resource` predicate is usable and this is the first catalog where a resource does ordering
-- work. ⚠ `hero` is deliberately unset: the Templar sub-tree id has not been read from a live
-- client, and inventing one would silently bind nothing. Unset means "any hero tree", which on
-- Herald of the Sun offers a Templar-authored priority — acceptable while this addon has one
-- Templar user, and the one line to tighten once the id is known. ⚠ The Expurgation row is
-- `383346`, the debuff that LANDS, not `383344`, the passive talent node — confirmed in client
-- 2026-08-19 by icon. It binds only if the player has added Expurgation to Tracked Buffs; if
-- not, `aura:expurgation` reads UNKNOWN and its marker stays DARK rather than reading as "the
-- DoT is down".
local ADDON, ns = ...

ns.Catalog.Register{
  spec = 70,
  name = "Retribution / Templar",
  power = "HolyPower",

  abilities = {
    { id = "execution_sentence", spell = 343527 },
    { id = "avenging_wrath", spell = 31884 },
    { id = "wake_of_ashes", spell = 255937, alt = { 427453 } },
    { id = "divine_toll", spell = 375576 },
    { id = "templars_verdict", spell = 85256, alt = { 383328 } },
    { id = "divine_storm", spell = 53385 },
    { id = "blade_of_justice", spell = 184575 },
    { id = "judgment", spell = 20271, alt = { 24275 } },
    { id = "crusader_strike", spell = 35395, alt = { 407480 } },
    { id = "expurgation", spell = 383346, family = "auras", unit = "target" },
  },

  -- Node + entry from `knowledge/classes/paladin/retribution/ability-inventory.tsv`.
  talents = {
    { id = "holy_flames", node = 109371, entry = 115438, spell = 406545 },
    { id = "radiant_glory", node = 81549, entry = 102525, spell = 458359 },
  },

  -- Entry order IS the authored priority; `Catalog.OrderCheck` reports when the player's
  -- Cooldown Manager disagrees with it.
  entries = {
    -- 1 · execution_sentence. 1. A PLACED cooldown, not a press-on-cooldown one. Three markers,
    -- one cue key, so the AND-only band grammar unions them into a single badge.
    { id = "execution_sentence", ability = "execution_sentence",
      markers = {
        { id = "es_awaits_wrath_ready",
          cue = "blocked",
          when = {
            { "ready", "execution_sentence" },
            { "talent", "radiant_glory", negate = true },
            { "ready", "avenging_wrath" },
          },
        },
        { id = "es_awaits_wrath",
          cue = "blocked",
          when = { { "ready", "execution_sentence" }, { "talent", "radiant_glory", negate = true } },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 15,
          },
        },
        { id = "es_awaits_wake",
          cue = "blocked",
          when = { { "ready", "execution_sentence" } },
          display = {
            ability = "wake_of_ashes",
            beyond = 1.5,
            kind = "sealed-cooldown-range",
          },
        },
      },
    },
    -- 2 · avenging_wrath. 2. The window everything aligns into.
    { id = "avenging_wrath", ability = "avenging_wrath",
      markers = {
        { id = "aw_awaits_expurgation",
          cue = "blocked",
          when = {
            { "ready", "avenging_wrath" },
            { "talent", "holy_flames" },
            { "aura", "expurgation", negate = true },
          },
        },
      },
    },
    -- 3 · wake_of_ashes. 3. One row, two lives, selected by identity.
    { id = "wake_of_ashes", ability = "wake_of_ashes",
      scan_when = {
        { { "identity", "wake_of_ashes", "base" }, { "ready", "wake_of_ashes" } },
        { { "identity", "wake_of_ashes", "transformed" } },
      },
      markers = {
        { id = "woa_starved",
          cue = "starved",
          when = { { "affordable", "wake_of_ashes", negate = true } },
        },
        { id = "woa_awaits_wrath",
          cue = "blocked",
          when = {
            { "identity", "wake_of_ashes", "base" },
            { "ready", "wake_of_ashes" },
            { "talent", "radiant_glory", negate = true },
          },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 6,
          },
        },
        { id = "woa_awaits_sentence",
          cue = "blocked",
          when = { { "identity", "wake_of_ashes", "base" }, { "ready", "wake_of_ashes" } },
          display = {
            ability = "execution_sentence",
            kind = "sealed-cooldown-range",
            within = 4,
          },
        },
      },
    },
    -- 4 · divine_toll. 4. The one builder that genuinely must not be pressed at cap.
    { id = "divine_toll", ability = "divine_toll",
      markers = {
        { id = "dt_awaits_wrath",
          cue = "blocked",
          when = { { "ready", "divine_toll" }, { "talent", "radiant_glory", negate = true } },
          display = {
            ability = "avenging_wrath",
            kind = "sealed-cooldown-range",
            within = 15,
          },
        },
        { id = "dt_overcap",
          cue = "overcap",
          when = { { "ready", "divine_toll" }, { "resource", ">=", 5 } },
        },
      },
    },
    -- 5 · templars_verdict. 5. The default spender, and the wrong one in three states that look
    -- identical on the icon.
    { id = "templars_verdict", ability = "templars_verdict",
      scan_when = { { { "affordable", "templars_verdict" } } },
      markers = {
        { id = "tv_starved",
          cue = "starved",
          when = { { "affordable", "templars_verdict", negate = true } },
        },
        { id = "tv_awaits_blade",
          cue = "blocked",
          when = {
            { "proc", "blade_of_justice" },
            { "ready", "blade_of_justice" },
            { "resource", "<=", 4 },
            { "affordable", "templars_verdict" },
          },
        },
        { id = "tv_divine_storm_aoe",
          cue = "st_only",
          when = {
            { "aoe" },
            { "proc", "templars_verdict", negate = true },
            { "affordable", "templars_verdict" },
          },
        },
        { id = "tv_empyrean_power",
          cue = "blocked",
          when = {
            { "proc", "divine_storm" },
            { "proc", "templars_verdict", negate = true },
            { "affordable", "templars_verdict" },
          },
        },
      },
    },
    -- 6 · divine_storm. 6. Needs no mirror of the generator hold to steer the scan — it sits
    -- RIGHT of Templar's Verdict — but carries one anyway so the two spenders can be told
    -- apart.
    { id = "divine_storm", ability = "divine_storm",
      scan_when = { { { "affordable", "divine_storm" } } },
      markers = {
        { id = "ds_starved",
          cue = "starved",
          when = { { "affordable", "divine_storm", negate = true } },
        },
        { id = "ds_aoe_only",
          cue = "aoe_only",
          when = {
            { "aoe", negate = true },
            { "proc", "divine_storm", negate = true },
            { "affordable", "divine_storm" },
          },
        },
        { id = "ds_awaits_blade",
          cue = "blocked",
          when = {
            { "proc", "blade_of_justice" },
            { "ready", "blade_of_justice" },
            { "resource", "<=", 4 },
            { "affordable", "divine_storm" },
          },
        },
      },
    },
    -- 7 · blade_of_justice. 7. ONE cue, and it is the vocabulary's second positive.
    { id = "blade_of_justice", ability = "blade_of_justice",
      markers = {
        { id = "boj_opener",
          cue = "priority",
          when = {
            { "ready", "blade_of_justice" },
            { "talent", "holy_flames" },
            { "aura", "expurgation", negate = true },
          },
        },
      },
    },
    -- 8 · judgment. 8.
    { id = "judgment", ability = "judgment",
    },
    -- 9 · crusader_strike. 9.
    { id = "crusader_strike", ability = "crusader_strike",
    },
  },
}
