-- Lab.lua — GENERATED from specs/render-shelf.md Part 7. Do not edit this file.
--   uv run python -m wowkb.capart export lab
-- NO AUTHORITY. These treatments are drawn by the `/cap style` GALLERY only, on
-- cap-owned frames, so a treatment can be judged in the client before anyone adopts it.
-- They must NEVER reach the live overlay: `ns.LabStyle` may be read by StylePanel.lua and
-- nothing else, and `capart check` fails the build if any other file names it.
local ADDON, ns = ...

ns.LabStyle = {
  _comment = "NO AUTHORITY. Part 7. EMPTY, which is its correct resting state and not a defect. Nothing in `verdicts` or `cues` may name anything in here; capart enforces it. A treatment leaves the lab by being MOVED into Parts 1-6, never by being cited from there — which is what happened to every entry this block used to hold. A new idea gets a `lab` key, an `asks`, and a section in Part 7.",
  _sheet = {
    direction = "down",
    duty = 0.5,
    pitch_px = 16,
    texture = "stripes",
    texture_root = "Interface\\AddOns\\CombatAssistPlus\\Media\\",
    tile_px = 128,
  },
}
