-- Style.lua — GENERATED from specs/render-shelf.md Part 6. Do not edit this file.
--   uv run python -m wowkb.capart export lua
-- Data only: the logic that reads it is Treatment.lua and Paint.lua.
local ADDON, ns = ...

ns.Style = {
  arrival = {
    duration_s = 0.4,
    from_alpha = 0.00,
    from_scale = 2.00,
    smoothing = "OUT",
  },
  assets = {
    encode = "webp",
    icon_size = 56,
    quality = 90,
  },
  badges = {
    asset_root = "previews/assets/kenney",
    diameter_pct = 40,
    halo_falloff = 0.7,
    halo_texture = "halo",
    overhang_px = 2,
    padding_px = 3,
    plate = {
      alpha = 0.78,
      rgb = { 0.00, 0.00, 0.00 },
      scale = 1.12,
      texture = "plate",
    },
    rgb = { 0.95, 0.3, 0.3 },
    slots = {
      {
        anchor = "top-right-corner",
        id = 1,
      },
      {
        anchor = "left-of-1-along-top",
        id = 2,
      },
      {
        anchor = "below-1-along-right",
        id = 3,
      },
    },
    sprite_inset_pct = 16,
    texture_root = "Interface\\AddOns\\CombatAssistPlus\\Media\\badges\\",
    tint = "shelf",
  },
  budget = {
    max_base64_kb = 512,
  },
  cues = {
    blocked = {
      duration_s = 2.00,
      frames = {
        "timer_0",
        "timer_CW_25",
        "timer_CW_50",
        "timer_CW_75",
        "timer_100",
      },
      loop = "REPEAT",
      means = "held for a cooldown, or a readable dependency says the press would be wasted. The sweep is a steady pace, NOT elapsed time.",
      open = false,
      polarity = "negative",
      slot = 1,
    },
    capped = {
      duration_s = 1.2,
      frames = {
        "cards_stack",
        "cards_stack_high",
      },
      glow = {
        alpha_max = 0.55,
        alpha_min = 0.15,
        hz = 1.2,
        scale = 1.55,
      },
      loop = "BOUNCE",
      means = "charges are at max and the recharge is stalled — you are losing one right now",
      open = false,
      polarity = "positive",
      rgb = { 1.00, 0.78, 0.25 },
      slot = 3,
    },
    overcap = {
      duration_s = 1.2,
      frames = {
        "flask_half",
        "flask_full",
      },
      loop = "BOUNCE",
      means = "pressing would waste resource",
      open = false,
      polarity = "negative",
      slot = 2,
    },
    starved = {
      duration_s = 1.2,
      frames = {
        "flask_empty",
        "flask_half",
      },
      loop = "BOUNCE",
      means = "you cannot afford it",
      open = false,
      polarity = "negative",
      slot = 2,
    },
  },
  hatch = {
    alpha = 0.5,
    direction = "down",
    duty = 0.5,
    phase_pct = 50,
    pitch_px = 16,
    rgb = { 0.00, 0.00, 0.00 },
    texture = "stripes",
    texture_root = "Interface\\AddOns\\CombatAssistPlus\\Media\\",
    tile_px = 128,
    tint = "shelf",
  },
  motion = {
    tick_s = 0.025,
  },
  panel = {
    anchor = "BOTTOM",
    gap_px = 6,
    grow = "RIGHT",
    icon_px = 50,
    x = 0,
    y = 190,
  },
  ready = {
    _comment = "IN THE SCAN. One treatment, no roles, no motion. An icon either participates in the read or it does not; rank comes from row order and elimination, not from a hue ladder. Full brightness on a restrained AREA: additive, so it reads as a hot edge rather than as a wash, and it sits ON the icon rect so it can never bleed into a neighbour at any row gap.",
    alpha = 1.00,
    line_px = 2,
    rgb = { 1.00, 0.86, 0.45 },
  },
  ring = {
    corner_px = 4,
    frames = 16,
    grid = 4,
    gutter_px = 1,
    texture = "ring",
    texture_root = "Interface\\AddOns\\CombatAssistPlus\\Media\\",
    thickness_px = 2,
    tile_px = 64,
    tint = "shelf",
    travel_px = 5,
  },
  surfaces = {
    border_px = 1,
    count_tile = {
      font = "FRIZQT__.TTF",
      outline = "OUTLINE",
      size = 14,
    },
    icon_px = 56,
    proc_glow_alpha = 0.5,
    row_gap_px = 6,
    swipe = {
      alpha = 0.72,
      color = { 0.00, 0.00, 0.00 },
    },
  },
  text = {
    alpha_floor = 0.65,
    duty = 0.7,
    max_hz = 2.00,
  },
  verdicts = {
    below = {
      cues = {  },
      scan = true,
      swipe = false,
    },
    cd = {
      cues = {  },
      hatch = true,
      scan = false,
      swipe = true,
    },
    ["hold-readable"] = {
      cues = {
        "blocked",
      },
      scan = true,
      swipe = false,
    },
    ["hold-sealed"] = {
      cues = {
        "blocked",
      },
      scan = true,
      swipe = false,
    },
    overcap = {
      cues = {
        "overcap",
      },
      scan = true,
      swipe = false,
    },
    press = {
      cues = {  },
      scan = true,
      swipe = false,
    },
    ["press-promoted"] = {
      cues = {  },
      scan = true,
      swipe = false,
    },
    starved = {
      cues = {
        "starved",
      },
      scan = true,
      swipe = false,
    },
    weave = {
      cues = {  },
      scan = true,
      swipe = false,
    },
  },
  version = 2,
}
